Repository AY2223S2-CS2103T-T13-3/tp, pull requests merged in 2023-03, with the labels that each got.

#59 Made some Edit to the Edit UG
  docs/UserGuide.md
Labels: priority.HIGH, type.Documentation

#58 Update help and clear features in UG
  docs/UserGuide.md
Labels: type.Documentation

#60 Update Developer Guide for v1.1
  docs/DeveloperGuide.md
Labels: priority.HIGH, type.Documentation

#61 Add find, list user guides.
  docs/UserGuide.md
Labels: priority.HIGH, type.Documentation

#68 Update Javafx Ui
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: type.Task

#71 Branch add edit feature for v1.2
  README.md
  docs/DeveloperGuide.md
  docs/images/huangzz125.png
  docs/index.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditApplicationCommand.java
  src/main/java/seedu/address/logic/parser/EditApplicationCommandParser.java
  src/main/java/seedu/address/logic/parser/InternshipBookParser.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: enhancement, priority.HIGH

#74 Achieve MVP v1.2
  .github/workflows/gradle.yml
  src/main/java/seedu/address/ApplicationMainApp.java
  src/main/java/seedu/address/Main.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/ApplicationLogic.java
  src/main/java/seedu/address/logic/ApplicationLogicManager.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindApplicationCommand.java
  src/main/java/seedu/address/logic/commands/ListApplicationCommand.java
  src/main/java/seedu/address/logic/parser/FindApplicationCommandParser.java
  src/main/java/seedu/address/logic/parser/InternshipBookParser.java
  src/main/java/seedu/address/model/application/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/util/ApplicationSampleDataUtil.java
  src/main/java/seedu/address/storage/ApplicationStorage.java
  src/main/java/seedu/address/storage/ApplicationStorageManager.java
  src/main/java/seedu/address/storage/InternshipBookStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedApplication.java
  src/main/java/seedu/address/storage/JsonInternshipBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableInternshipBook.java
  src/main/java/seedu/address/ui/ApplicationCard.java
  src/main/java/seedu/address/ui/ApplicationListPanel.java
  src/main/java/seedu/address/ui/ApplicationMainWindow.java
  src/main/java/seedu/address/ui/ApplicationUiManager.java
  src/main/java/seedu/address/ui/ApplicationUiPart.java
  src/main/resources/view/ApplicationListCard.fxml
  src/main/resources/view/ApplicationListPanel.fxml
  src/main/resources/view/ApplicationMainWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: priority.HIGH

#77 Fix bug that prevents user from editing status of existing application
  src/main/java/seedu/address/model/application/UniqueApplicationList.java
Labels: bug

#104 Add Tags to Applications and Exit Command
  src/main/java/seedu/address/logic/commands/AddApplicationCommand.java
  src/main/java/seedu/address/logic/commands/EditApplicationCommand.java
  src/main/java/seedu/address/logic/commands/ExitSprintCommand.java
  src/main/java/seedu/address/logic/parser/AddApplicationCommandParser.java
  src/main/java/seedu/address/logic/parser/ApplicationCliSyntax.java
  src/main/java/seedu/address/logic/parser/EditApplicationCommandParser.java
  src/main/java/seedu/address/logic/parser/InternshipBookParser.java
  src/main/java/seedu/address/model/application/Application.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/ApplicationSampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedApplication.java
  src/main/java/seedu/address/ui/ApplicationCard.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/test/java/seedu/address/testutil/ApplicationBuilder.java
Labels: priority.HIGH

#109 Add Clear Applications command
  src/main/java/seedu/address/logic/commands/ClearApplicationCommand.java
  src/main/java/seedu/address/logic/parser/InternshipBookParser.java
Labels: priority.HIGH

#114 Add testing for add command and edit command. For add command, add in…
  src/test/java/seedu/address/logic/commands/AddApplicationCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddApplicationCommandTest.java
  src/test/java/seedu/address/logic/commands/EditApplicationCommandTest.java
  src/test/java/seedu/address/logic/commands/EditApplicationDescriptorTest.java
Labels: type.Testing

#113 Improve DG for v1.3
  docs/DeveloperGuide.md
Labels: type.Documentation

#118 IMPORTANT. BUILD FIX. PULL THIS IMMEDIATELY.
  .github/workflows/gradle.yml
  docs/DeveloperGuide.md
  docs/diagrams/AddApplicationSequenceDiagram.puml
  docs/images/AddApplicationSequenceDiagram.png
  src/main/java/seedu/address/logic/ApplicationLogic.java
  src/main/java/seedu/address/logic/ApplicationLogicManager.java
  src/main/java/seedu/address/model/ApplicationModel.java
  src/main/java/seedu/address/model/ApplicationModelManager.java
  src/main/java/seedu/address/model/InternshipBook.java
  src/main/java/seedu/address/model/ReadOnlyInternshipBook.java
  src/main/java/seedu/address/model/application/Application.java
  src/main/java/seedu/address/model/application/CompanyEmail.java
  src/main/java/seedu/address/model/application/CompanyName.java
  src/main/java/seedu/address/model/application/Role.java
  src/main/java/seedu/address/model/application/Status.java
  src/main/java/seedu/address/model/application/UniqueApplicationList.java
  src/main/java/seedu/address/model/application/exceptions/ApplicationNotFoundException.java
  src/main/java/seedu/address/model/application/exceptions/DuplicateApplicationException.java
  src/main/resources/view/DarkTheme.css
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/EditApplicationCommandTest.java
  src/test/java/seedu/address/logic/commands/EditTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/FindApplicationCommandTest.java
  src/test/java/seedu/address/logic/commands/ListApplicationCommandTest.java
Labels: priority.HIGH

#130 Update DG details for Clear Applications command
  docs/DeveloperGuide.md
  docs/diagrams/ClearApplicationsSequenceDiagram.puml
  docs/images/ClearApplicationsSequenceDiagram.png
Labels: priority.HIGH

#129 Fix bug with list command not showing all applications
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ListApplicationCommand.java
  src/main/java/seedu/address/logic/commands/SortApplicationCommand.java
Labels: bug

#132 Update DG details for Exit sprINT command
  docs/DeveloperGuide.md
  docs/diagrams/ExitSprintSequenceDiagram.puml
  docs/images/ExitSprintSequenceDiagram.png
Labels: priority.HIGH

#131 Pull UGDG changes from branch to master
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/EditApplicationSequenceDiagram.puml
  docs/diagrams/FindApplicationSequenceDiagram.puml
  docs/images/FindApplicationSequenceDiagram.png
Labels: type.Documentation

#139 Resolve bug with list of applications flipping upon app restart
  src/main/java/seedu/address/model/util/ApplicationSampleDataUtil.java
  src/main/java/seedu/address/storage/JsonSerializableInternshipBook.java
Labels: bug

#137 Add tests related to parsing
  src/main/java/seedu/address/logic/parser/AddApplicationCommandParser.java
  src/main/java/seedu/address/logic/parser/ApplicationParserUtil.java
  src/main/java/seedu/address/storage/ApplicationStorageManager.java
  src/test/java/seedu/address/logic/ApplicationLogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ApplicationCommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddApplicationCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ApplicationCommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/ApplicationParserUtilTest.java
  src/test/java/seedu/address/logic/parser/InternshipBookParserTest.java
  src/test/java/seedu/address/testutil/TypicalApplications.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.HIGH, type.Testing

#140 Pull DG changes in branch-v1.3-features to master
  docs/DeveloperGuide.md
  docs/diagrams/AddApplicationSequenceDiagram.puml
  docs/diagrams/EditApplicationSequenceDiagram.puml
Labels: type.Documentation

#141 Improve UG for v1.3 and UG review
  docs/UserGuide.md
Labels: priority.HIGH, type.Documentation

#145 Add section on sort implementation in DG
  docs/DeveloperGuide.md
  docs/diagrams/CommandExecutionWorkflow.puml
  docs/diagrams/SortApplicationSequenceDiagram.puml
  docs/images/CommandExecutionWorkflow.png
  docs/images/SortApplicationSequenceDiagram.png
Labels: type.Documentation

#151 Proofread UserGuide
  docs/UserGuide.md
Labels: type.Documentation

#156 Fix UG TOC
  docs/UserGuide.md
Labels: priority.HIGH, type.Documentation

#158 Change UI image in UG
  docs/UserGuide.md
  docs/UserGuideOriginal.md
  docs/images/Ui.png
  docs/images/UiMockup.png
Labels: type.Documentation

#157 Modify sort deadline command
  src/main/java/seedu/address/logic/commands/ListApplicationCommand.java
  src/main/java/seedu/address/logic/commands/SortApplicationCommand.java
  src/main/java/seedu/address/model/application/ApplicationHasTaskPredicate.java
Labels: type.Enhancement

#160 Color fixes for pie chart
  src/main/java/seedu/address/model/statistic/Statistic.java
  src/main/java/seedu/address/ui/StatisticPanel.java
  src/main/resources/view/StatisticPanel.fxml
Labels: priority.HIGH, type.Enhancement

#168 Change alphabetical sorting to focus on Role
  src/main/java/seedu/address/model/application/AlphabeticalComparator.java
Labels: type.Enhancement

#172 Improve UG following peer review
  docs/UserGuide.md
  docs/images/LabelledUi.png
  docs/images/Ui.png
  docs/images/UiAfterAddTask.png
  src/main/java/seedu/address/logic/commands/AddApplicationCommand.java
Labels: type.Documentation

#178 Make tags editing more explicit in UG
  docs/UserGuide.md
Labels: type.Documentation

#179 Clarify tag syntax in UG
  docs/UserGuide.md
Labels: type.Documentation
