Repository AY2223S2-CS2103T-T13-3/tp, pull requests merged in 2023-04, with the labels that each got.

#223 Fix help window and find command problems
  src/main/java/seedu/sprint/logic/commands/FindCommand.java
  src/main/java/seedu/sprint/logic/parser/FindCommandParser.java
  src/main/java/seedu/sprint/model/application/NameContainsKeywordsPredicate.java
  src/main/java/seedu/sprint/ui/HelpWindow.java
Labels: priority.HIGH

#224 Xylus Bug Fixes
  src/main/java/seedu/sprint/logic/commands/AddApplicationCommand.java
  src/main/java/seedu/sprint/model/tag/Tag.java
  src/main/java/seedu/sprint/storage/JsonSerializableInternshipBook.java
Labels: bug, priority.HIGH

#226 Give user feedback when there are no deadlines to sort
  docs/UserGuide.md
  docs/images/HelpWindow.png
  docs/images/LabelledUi.png
  docs/images/UiAfterAddTask.png
  docs/images/helpMessage.png
  src/main/java/seedu/sprint/logic/commands/SortCommand.java
Labels: type.Enhancement

#227 Improvements to UG
  docs/UserGuide.md
  docs/images/LabelledUi.png
  docs/images/Ui.png
  docs/images/UiAfterAddTask.png
Labels: type.Documentation

#232 Create draft of Hui Xuan's PPP
  docs/team/huixuant.md
Labels: type.Documentation

#233 Improve UG
  docs/UserGuide.md
  docs/UserGuideOriginal.md
Labels: type.Documentation

#235 Fixed task-related test cases
  docs/UserGuideOriginal.md
  src/test/data/JsonSerializableInternshipBookTest/typicalApplicationsInternshipBook.json
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/sprint/logic/LogicManagerTest.java
  src/test/java/seedu/sprint/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/sprint/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/sprint/logic/commands/EditApplicationCommandTest.java
  src/test/java/seedu/sprint/logic/commands/EditTaskCommandTest.java
  src/test/java/seedu/sprint/testutil/TypicalApplications.java
Labels: type.Testing

#237 Fix formatting issues in UG
  docs/UserGuide.md
Labels: type.Documentation

#239 Made small adjustments to UG
  docs/UserGuide.md
Labels: documentation

#240 Added Jiaxin's PPP
  docs/team/yaojiax.md
Labels: documentation, priority.HIGH, type.Documentation

#241 Add test cases for Sort, List commands
  src/main/java/seedu/sprint/logic/commands/SortCommand.java
  src/test/java/seedu/sprint/logic/commands/FindCommandTest.java
  src/test/java/seedu/sprint/logic/commands/ListCommandIntegrationTest.java
  src/test/java/seedu/sprint/logic/commands/ListCommandTest.java
  src/test/java/seedu/sprint/logic/commands/SortCommandTest.java
  src/test/java/seedu/sprint/logic/parser/InternshipBookParserTest.java
  src/test/java/seedu/sprint/logic/parser/SortCommandParserTest.java
Labels: type.Testing

#242 Improve DG for submission
  docs/DeveloperGuide.md
  docs/diagrams/SortApplicationSequenceDiagram.puml
  docs/images/SortApplicationSequenceDiagram.png
  docs/images/SortDeadlineWithNoDeadlines.png
  docs/images/SortSequenceDiagram.png
Labels: type.Documentation

#243 Add FindCommandParser tests
  src/main/java/seedu/sprint/model/application/NameContainsKeywordsPredicate.java
  src/test/java/seedu/sprint/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/sprint/logic/parser/FindCommandParserTest.java
Labels: priority.HIGH, type.Testing

#246 Add add-app, clear, and exit manual testing information in Appendix
  docs/DeveloperGuide.md
Labels: type.Documentation

#247 Add tests for Statistic entity
  src/main/java/seedu/sprint/model/statistic/Statistic.java
  src/test/java/seedu/sprint/model/statistic/StatisticTest.java
Labels: type.Testing

#248 Code quality adjustments
  src/main/java/seedu/sprint/logic/commands/FindCommand.java
  src/main/java/seedu/sprint/logic/parser/FindCommandParser.java
  src/main/java/seedu/sprint/model/application/ApplicationContainsKeywordsPredicate.java
  src/main/java/seedu/sprint/model/application/NameContainsKeywordsPredicate.java
  src/main/java/seedu/sprint/ui/HelpWindow.java
  src/test/data/JsonInternshipBookStorageTest/invalidAndValidApplicationInternshipBook.json
  src/test/data/JsonInternshipBookStorageTest/invalidApplicationInternshipBook.json
  src/test/java/seedu/sprint/logic/commands/ApplicationCommandTestUtil.java
  src/test/java/seedu/sprint/logic/commands/FindCommandTest.java
  src/test/java/seedu/sprint/logic/commands/ListCommandIntegrationTest.java
  src/test/java/seedu/sprint/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/sprint/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/sprint/logic/parser/InternshipBookParserTest.java
  src/test/java/seedu/sprint/model/ModelManagerTest.java
  src/test/java/seedu/sprint/storage/StorageManagerTest.java
Labels: type.Testing

#258 Merge Branch-v1.4 into Master
  docs/UserGuide.md
  src/main/java/seedu/sprint/logic/commands/AddApplicationCommand.java
  src/main/java/seedu/sprint/logic/commands/FindCommand.java
  src/main/java/seedu/sprint/logic/commands/SortCommand.java
  src/main/java/seedu/sprint/logic/parser/FindCommandParser.java
  src/main/java/seedu/sprint/model/ModelManager.java
  src/main/java/seedu/sprint/model/application/AlphabeticalComparator.java
  src/main/java/seedu/sprint/model/application/Application.java
  src/main/java/seedu/sprint/model/application/ApplicationContainsKeywordsPredicate.java
  src/main/java/seedu/sprint/model/application/DeadlineComparator.java
  src/main/java/seedu/sprint/model/application/NameContainsKeywordsPredicate.java
  src/main/java/seedu/sprint/model/application/UniqueApplicationList.java
  src/main/java/seedu/sprint/model/statistic/Statistic.java
  src/main/java/seedu/sprint/model/tag/Tag.java
  src/main/java/seedu/sprint/model/task/Deadline.java
  src/main/java/seedu/sprint/model/task/Task.java
  src/main/java/seedu/sprint/storage/JsonSerializableInternshipBook.java
  src/main/java/seedu/sprint/ui/HelpWindow.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/notJsonFormatAddressBook.json
  src/test/data/JsonInternshipBookStorageTest/invalidAndValidApplicationInternshipBook.json
  src/test/data/JsonInternshipBookStorageTest/invalidApplicationInternshipBook.json
  src/test/data/JsonInternshipBookStorageTest/notJsonFormatInternshipBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/JsonSerializableInternshipBookTest/duplicateApplicationInternshipBook.json
  src/test/data/JsonSerializableInternshipBookTest/invalidApplicationInternshipBook.json
  src/test/data/JsonSerializableInternshipBookTest/typicalApplicationsInternshipBook.json
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/sprint/logic/LogicManagerTest.java
  src/test/java/seedu/sprint/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/sprint/logic/commands/ApplicationCommandTestUtil.java
  src/test/java/seedu/sprint/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/sprint/logic/commands/EditApplicationCommandTest.java
  src/test/java/seedu/sprint/logic/commands/EditTaskCommandTest.java
  src/test/java/seedu/sprint/logic/commands/FindCommandTest.java
  src/test/java/seedu/sprint/logic/commands/ListCommandIntegrationTest.java
  src/test/java/seedu/sprint/logic/commands/ListCommandTest.java
  src/test/java/seedu/sprint/logic/commands/SortCommandTest.java
  src/test/java/seedu/sprint/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/sprint/logic/parser/DeleteApplicationCommandParserTest.java
  src/test/java/seedu/sprint/logic/parser/EditApplicationCommandParserTest.java
  src/test/java/seedu/sprint/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/sprint/logic/parser/InternshipBookParserTest.java
  src/test/java/seedu/sprint/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/sprint/model/ModelManagerTest.java
  src/test/java/seedu/sprint/model/statistic/StatisticTest.java
  src/test/java/seedu/sprint/storage/JsonAdaptedApplicationTest.java
  src/test/java/seedu/sprint/storage/JsonInternshipBookStorageTest.java
  src/test/java/seedu/sprint/storage/JsonSerializableInternshipBookTest.java
  src/test/java/seedu/sprint/storage/StorageManagerTest.java
  src/test/java/seedu/sprint/testutil/TypicalApplications.java
Labels: priority.HIGH

#259 Update DG with Tag truncation feature flaw enhancement
  docs/DeveloperGuide.md
  docs/images/LongAndMultipleTags.png
  docs/images/TagWrapAround.png
  src/main/java/seedu/sprint/ui/ApplicationCard.java
  src/main/resources/view/ApplicationCard.fxml
Labels: priority.HIGH

#260 Made edits for UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Notspecificerrormessage.png
Labels: documentation, priority.HIGH

#264 Fix HelpWindow
  src/main/java/seedu/sprint/ui/HelpWindow.java
Labels: bug

#263 UG Final run through
  docs/UserGuide.md
Labels: type.Documentation

#265 Update misnamed classes in DG
  docs/DeveloperGuide.md
  docs/diagrams/AddApplicationSequenceDiagram.puml
  docs/diagrams/ClearApplicationsSequenceDiagram.puml
  docs/diagrams/CommandExecutionWorkflow.puml
  docs/images/AddApplicationSequenceDiagram.png
  docs/images/ClearApplicationsSequenceDiagram.png
  docs/images/ClearSequenceDiagram.png
  docs/images/CommandExecutionWorkflow.png
Labels: type.Documentation

#271 Reduce Xylus' PPP to 2 pages
  docs/team/xyluschen.md
Labels: type.Documentation

#272 Fix formatting for Xylus' PPP
  docs/team/xyluschen.md
Labels: type.Documentation

#274 Clarify `sort` behaviour in UG
  docs/UserGuide.md
Labels: type.Documentation

#277 Important changes and fixes
  docs/team/xyluschen.md
  src/main/java/seedu/sprint/logic/commands/AddTaskCommand.java
  src/main/java/seedu/sprint/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/sprint/logic/commands/EditTaskCommand.java
  src/test/data/JsonSerializableInternshipBookTest/typicalApplicationsInternshipBook.json
  src/test/java/seedu/sprint/logic/commands/ApplicationCommandTestUtil.java
  src/test/java/seedu/sprint/testutil/TypicalApplications.java
Labels: bug, priority.HIGH, type.Documentation

#287 Clarify `sort` behaviour in DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#297 Add user scenarios for edit-app and delete-app
  docs/UserGuide.md
Labels: type.Documentation

#298 UG updates
  docs/UserGuide.md
Labels: type.Documentation

#302 Fix formatting issues and some hyperlinks
  docs/UserGuide.md
Labels: type.Documentation

#303 Update screenshots in UG
  docs/UserGuide.md
  docs/images/BeforeAfterAddTask1.png
  docs/images/BeforeAfterAddTask2.png
  docs/images/BeforeAfterEditApp1.png
  docs/images/BeforeAfterEditApp2.png
  docs/images/BeforeAfterFind1.png
  docs/images/BeforeAfterFind2.png
  docs/images/BeforeAfterSort1.png
  docs/images/BeforeAfterSort2.png
  docs/images/BeforeAfterStatistics1.png
  docs/images/BeforeAfterStatistics2.png
  docs/images/BeforeAfterUndo1.png
  docs/images/BeforeAfterUndo2.png
  docs/images/Tag.png
Labels: type.Documentation

#304 Improve example in sort command
  docs/UserGuide.md
Labels: type.Documentation

#305 Add contact us details
  docs/AboutUs.md
  docs/UserGuide.md
Labels: type.Documentation
